#!/bin/bash

_other_installs () {
   if [[ $OTHER_INSTALLS != "None" ]]
   then
    apt install $OTHER_INSTALLS -y
   fi
   }
_externals () {
   if [[ $OTHER_CMD != "None" ]]
   then
      $OTHER_CMD
   fi
   }
    
apt update && apt upgrade -y
apt install git -y
_other_installs
pip3 install -U pip
git clone https://github.com/Nobita-xd/music3 Github_Repo
cd Github_Repo
apt install git curl python3-pip ffmpeg -y
apt-get install -y nodejs
pip3 install -U -r requirements.txt
_externals
python3 -m YukkiMusic
